### ISSUE TITLE
Header containing CPP code is forcefuly formatted as ObjC

### ISSUE THREAD

**Issue by szalap** [benoitsan/BBUncrustifyPlugin-Xcode#118]
When having some C++ code mixed with ObjC in .h file, the formatting is screwed up when it comes to double colons for namespaces.

Code like this: 
- (Project::Something) getSomethingFor: (Project::Item) item; 
turns into this monster (what, of course, raises errors):
- (Project : : Something) getSomethingFor: (Project : : Item) item;

I've tested this with original Uncrustify and the file is recognized as CPP and formatted as such, so the spaces are not added in there.

**Comment by benoitsan** [comment]
Not tested but I think it's because we add `OC` (Objective-C language) in the language `-l` parameter if the file is a header file (see https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/blob/master/Classes/CFOUncrustifyFormatter.m#L67-L72). Removing this could cause (I suppose) a bad reformatting for pure objc header files so I don't know how to fix this.

**Comment by szalap** [comment]
You're right, this is directly related to setting OC language based on header and source type.

Is there any clean and nice way of detecting if the .h file (and maybe even .m) has CPP code inside? 
The language flag could be set as it is now, but when CPP code is detected then change the flag rather to CPP.

**Comment by ericforget** [comment]
The fix is simple. We need to pass "OC+" for the parameter. It will support Objective-C, Objective-C++, and C++.

**Comment by benoitsan** [comment]
Fixed. See https://github.com/benoitsan/BBUncrustifyPlugin-Xcode/pull/131
