### ISSUE TITLE
Xcode 6.2 with Alcatraz

### ISSUE THREAD

**Issue by TofPlay** [benoitsan/BBUncrustifyPlugin-Xcode#91]
Hi,
![xcode 6 2 - bbuncrustifyplugin preferences](https://cloud.githubusercontent.com/assets/1082222/6728611/436959d8-ce2b-11e4-8340-fdc1ae4e9c78.png)
This menu option does not display anything
Regards
Tof

**Comment by benoitsan** [comment]
It's not the first time I got this issue. It displays nothing because the xib file is missing. I still don't understand the reason why the xib is sometimes missing in the built product. 

Check that the file `UncrustifyPlugin.xcplugin/Contents/Resources/XCFPreferencesWindowController.nib` exists. 

A workaround is to reinstall the plugin.

![screen_shot_2015-03-19_at_20_33_35](https://cloud.githubusercontent.com/assets/528847/6739182/4c05157c-ce77-11e4-923b-a6f5181f0851.jpg)

**Comment by TofPlay** [comment]
Where I can find UncrustifyPlugin.xcplugin?

**Comment by TofPlay** [comment]
I reinstall the plugin but the nib still missing

**Comment by TofPlay** [comment]
I found!
I have to remove the folder 
```
~/Library/Application Support/Alcatraz/Plug-ins/BBUncrustifyPlugin
```
to force Alcatraz to rebuild your plugin.

**Comment by benoitsan** [comment]
OK, it's weird. As I said, I already had this issue with xib file but I don't understand the reason, don't know if it's an issue in my config or a bug in Xcode.
Yeah, when you got this, the best thing is to delete the whole plugin.
Good that you fixed it by your own.
